name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5

    - name: Set up Go
      uses: actions/setup-go@bfdd3570ce990073878bf10f6b2d79082de49492
      with:
        go-version-file: go.mod

    - name: Build w/ CGO
      run: GOOS=linux go build

    - name: Build w/o CGO
      run: GOOS=linux CGO_ENABLED=0 go build

    - name: WASM Build
      run: GOOS=js GOARCH=wasm go build

    - name: Test decompression w/ CGO
      run: go test -v -run TestPublicKeyDecompression -count 100

    - name: Test decompression w/o CGO
      run: CGO_ENABLED=0 go test -v -run TestPublicKeyDecompression -count 100

    - name: Test w/ CGO
      run: go test -v ./...

    - name: Test w/o CGO
      run: CGO_ENABLED=0 go test -v ./...

    - name: Test race w/ CGO
      run: go test -race -v ./...

    - name: Test race w/o CGO
      run: go test -tags=ecies_test_race -race -v ./...

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5

    - name: Set up Go
      uses: actions/setup-go@bfdd3570ce990073878bf10f6b2d79082de49492
      with:
        go-version-file: go.mod

    - name: Lint
      uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0
      with:
        version: v2.13.2
